// scripts/generate-size-utils.js
const fs = require('fs');
const path = require('path');

const remScale = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 72, 80, 96];
const remValue = n => n === 0 ? '0' : (n >= 100 ? `${n}rem` : `${n/4}rem`); // if you prefer 1 unit = 0.25rem
// If you already use specific mapping, replace above logic with a map array.

const fractions = {
  '1/2': '50%',
  '1/3': '33.3333%',
  '2/3': '66.6667%',
  '1/4': '25%',
  '3/4': '75%',
  '1/5': '20%',
  '2/5': '40%',
  '3/5': '60%',
  '4/5': '80%'
};

const percentSteps = Array.from({length: 20}, (_,i) => (i+1)*5); // 5..100%
const viewports = [10,20,30,40,50,60,70,80,90,100];

function escClass(s){ return s.replace(/\//g, '\\/').replace(/%/g, 'p').replace(/vw$/,'vw'); }

let out = `/* Auto-generated by scripts/generate-size-utils.js — include as optional dist/quanta.size-utils.css */\n\n`;

function addClass(selector, prop, val){
  out += `.${selector} { ${prop}: ${val}; }\n`;
}

remScale.forEach(n => {
  const key = n.toString();
  const val = remValue(n);
  addClass(`w-${key}`, 'width', val);
  addClass(`h-${key}`, 'height', val);
  addClass(`min-w-${key}`, 'min-width', val);
  addClass(`max-w-${key}`, 'max-width', val);
  addClass(`min-h-${key}`, 'min-height', val);
  addClass(`max-h-${key}`, 'max-height', val);
});

Object.entries(fractions).forEach(([k,v])=>{
  const esc = escClass(k);
  addClass(`w-${esc}`, 'width', v);
  addClass(`h-${esc}`, 'height', v);
  addClass(`min-w-${esc}`, 'min-width', v);
  addClass(`max-w-${esc}`, 'max-width', v);
  addClass(`min-h-${esc}`, 'min-height', v);
  addClass(`max-h-${esc}`, 'max-height', v);
});

percentSteps.forEach(p=>{
  const key = `${p}p`;
  const val = `${p}%`;
  addClass(`w-${key}`, 'width', val);
  addClass(`h-${key}`, 'height', val);
  addClass(`min-w-${key}`, 'min-width', val);
  addClass(`max-w-${key}`, 'max-width', val);
  addClass(`min-h-${key}`, 'min-height', val);
  addClass(`max-h-${key}`, 'max-height', val);
});

viewports.forEach(v=>{
  const key = `${v}vw`;
  const val = `${v}vw`;
  addClass(`w-${key}`, 'width', val);
  addClass(`h-${key}`, 'height', val);
  addClass(`min-w-${key}`, 'min-width', val);
  addClass(`max-w-${key}`, 'max-width', val);
  addClass(`min-h-${key}`, 'min-height', val);
  addClass(`max-h-${key}`, 'max-height', val);
});

const outPath = path.join(__dirname, '..', 'dist', 'quanta.size-utils.css');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);
console.log('generated ->', outPath);
